processor:
  docPaths: []
  ignoreTypes:
    - ".*List$"
    - "AFI"
    - "SAFI"
    - "AddressFamily"
    - "SRv6Function"
    - "RouterRole"
    - "OriginType"
    - "RouterRef"
    - "RouterSelector"
    - "RouterTarget"
    - "LocalSecretRef"
    - "RouterStatus"
    - "ResolvedRouterConfig"
    - "BGPPeerBFD"
    - "BGPPeerGracefulRestart"
    - "BGPPeerAuthentication"
    - "Community"
    - "Prefix"
    - "RedistributeSource"
    - "AdvertisementOriginateType"
    - "AdvertisementOriginateFrom"
    - "AdvertisementPolicyRef"
    - "BGPAdvertisement"
    - "BGPAdvertisementSpec"
    - "BGPAdvertisementStatus"
    - "BGPCommunitySet"
    - "BGPCommunitySetType"
    - "BGPCommunitySetSpec"
    - "BGPCommunitySetStatus"
    - "BGPPeerState"
    - "SendCommunityType"
    - "MaxPrefixShutdownAction"
    - "BGPMaximumPrefix"
    - "BGPPeer"
    - "BGPPeerSpec"
    - "BGPPeerStatus"
    - "BGPRouterPhase"
    - "BGPRouter"
    - "BGPRouterSpec"
    - "BGPRouterStatus"
    - "BGPRouterPeerSummary"
    - "BGPVRFInstance"
    - "BGPVRFInstanceSpec"
    - "BGPVRFInstanceStatus"
    - "RouteTarget"
    - "BGPPolicyDirection"
    - "BGPPolicyAction"
    - "BGPPolicy"
    - "BGPPolicySpec"
    - "BGPPolicyTerm"
    - "BGPPolicyMatch"
    - "BGPPolicySetActions"
    - "BGPPolicyStatus"
    - "ASPathMatchType"
    - "ASPathFilter"
    - "EVPNRouteType"
    - "BGPOrigin"
    - "AsPathSet"
    - "NextHopSet"
    - "CommunitySet"
    - "ExtendedCommunitySet"
    - "BGPPrefixList"
    - "BGPPrefixListEntry"
    - "BGPPrefixListSpec"
    - "BGPPrefixListStatus"
  ignoreFields: []

render:
  kubernetes: {}
  markdown:
    mediaWidth: 80
    anchorLink: true
    tableHideEmpty: true
