processor:
  docPaths: []
  ignoreTypes:
    - ".*List$"
    - "NetworkGateway"
    - "NetworkGatewaySpec"
    - "NetworkGatewayStatus"
    - "NetworkRule"
    - "NetworkRuleBackend"
    - "NetworkRuleProtocol"
    - "NetworkRuleSpec"
    - "NetworkRuleStatus"
  ignoreFields: []

render:
  kubernetes: {}
  markdown:
    mediaWidth: 80
    anchorLink: true
    tableHideEmpty: true
