apiVersion: network.datumapis.com/v1alpha1
kind: NetworkRule
metadata:
  name: vpc-a-https
  namespace: galactic-system
spec:
  vpcRef: vpc-a
  vipAddresses:
    - 2001:db8:1::10
  protocol: tcp
  port: 443
  backendSelector:
    matchLabels:
      app: web
  backendPort: 8443
