// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *ServiceEndpoint) DeepCopyInto(out *ServiceEndpoint) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *ServiceEndpoint) DeepCopy() *ServiceEndpoint {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpoint)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ServiceEndpointList) DeepCopyInto(out *ServiceEndpointList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ServiceEndpointList) DeepCopy() *ServiceEndpointList {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointList)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ServiceRoutePolicy) DeepCopyInto(out *ServiceRoutePolicy) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ServiceRoutePolicy) DeepCopy() *ServiceRoutePolicy {
	if in == nil {
		return nil
	}
	out := new(ServiceRoutePolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceRoutePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ServiceRoutePolicyList) DeepCopyInto(out *ServiceRoutePolicyList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceRoutePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ServiceRoutePolicyList) DeepCopy() *ServiceRoutePolicyList {
	if in == nil {
		return nil
	}
	out := new(ServiceRoutePolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceRoutePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ServiceRoutePolicySpec) DeepCopyInto(out *ServiceRoutePolicySpec) {
	*out = *in
	in.ServiceRef.DeepCopyInto(&out.ServiceRef)
	in.AttachmentSelector.DeepCopyInto(&out.AttachmentSelector)
	if in.ProtocolPorts != nil {
		in, out := &in.ProtocolPorts, &out.ProtocolPorts
		*out = make([]ServiceRouteProtocolPort, len(*in))
		copy(*out, *in)
	}
}

func (in *ServiceRoutePolicyStatus) DeepCopyInto(out *ServiceRoutePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
}

func (in *ServiceEndpointReference) DeepCopyInto(out *ServiceEndpointReference) {
	*out = *in
}

func (in *ServiceEndpointReference) DeepCopy() *ServiceEndpointReference {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointReference)
	in.DeepCopyInto(out)
	return out
}
