apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network.datumapis.com_bgpadvertisements.yaml
  - network.datumapis.com_bgppeers.yaml
  - network.datumapis.com_bgppolicies.yaml
  - network.datumapis.com_bgprouters.yaml
  - network.datumapis.com_bgpvrfinstances.yaml
  - network.datumapis.com_networkegresspolicies.yaml
  - network.datumapis.com_networkgateways.yaml
  - network.datumapis.com_networkrules.yaml
  - network.datumapis.com_servicevipbindings.yaml
  - network.datumapis.com_nat66shards.yaml
